stages:
  - build
  - test
  - deploy

build_job:
  stage: build
  script:
    - echo "Building"

test_unit_job:
  stage: test
  script:
    - echo "Testing"

test_integration_job:
  stage: test
  script:
    - echo "Testing2"

deploy_job:
  stage: deploy_job
  script:
    - echo "Deploying"
