FROM ruby:2.2

ENV APP_HOME /app

WORKDIR $APP_HOME

COPY . ./

RUN echo "deb http://archive.debian.org/debian stretch main contrib" > /etc/apt/sources.list && \
    apt-get update && \
    apt-get install -y build-essential --no-install-recommends && \
    rm -rf /var/lib/apt/lists/* && \
    bundle install --no-cache

ENV POST_SERVICE_HOST post
ENV POST_SERVICE_PORT 5000
ENV COMMENT_SERVICE_HOST comment
ENV COMMENT_SERVICE_PORT 9292

CMD ["puma"]
