FROM ruby:2.2

ENV APP_HOME /app

WORKDIR $APP_HOME

RUN echo "deb http://archive.debian.org/debian stretch main" > /etc/apt/sources.list && \
    apt-get update && \
    apt-get install -y build-essential --no-install-recommends && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

COPY Gemfile* ./
RUN bundle install --no-rdoc --no-ri
COPY . ./

ENV COMMENT_DATABASE_HOST comment_db
ENV COMMENT_DATABASE comments

CMD ["puma"]
