---
- name: Docker installation
  hosts: docker
  remote_user: ubuntu
  become_method: sudo
  become: true
  vars:
    container_image: "varsentiev/otus-reddit:1.0"

  tasks:
  - name: Pull image
    community.docker.docker_image:
      name: "{{ container_image }}"
      source: pull

  - name: Create container
    community.docker.docker_container:
      image: "{{ container_image }}"
      state: started
      name: "reddit"
      ports:
      - "80:9292"
