FROM ubuntu:16.04

ENV APP_HOME /app

WORKDIR $APP_HOME

COPY . ./

RUN apt-get update && \
    apt-get install -y build-essential ruby ruby-dev --no-install-recommends && \
    rm -rf /var/lib/apt/lists/* && \
    gem install bundler -v 2.3.26 --no-ri --no-rdoc && \
    bundle install --no-cache

ENV POST_SERVICE_HOST post
ENV POST_SERVICE_PORT 5000
ENV COMMENT_SERVICE_HOST comment
ENV COMMENT_SERVICE_PORT 9292

CMD ["puma"]
